version: '3.8'

services:
  backend:
    build: ./backend
    container_name: aadesigners-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - API_BASE_URL=${API_BASE_URL:-http://98.130.15.198:3001}
      - CORS_ORIGINS=http://98.130.15.198,http://98.130.15.198:80,http://localhost:3000,http://localhost:5173
      - ADMIN_PASSWORD=admin123
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/database.db:/app/database.db
    networks:
      - aadesigners-network
    restart: unless-stopped

  frontend:
    build: .
    container_name: aadesigners-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=${API_BASE_URL:-http://98.130.15.198:3001}
    depends_on:
      - backend
    networks:
      - aadesigners-network
    restart: unless-stopped

networks:
  aadesigners-network:
    driver: bridge

volumes:
  uploads:
    driver: local 